### ISSUE TITLE
Update README.md to enter a Base URL

### ISSUE THREAD

**Issue by chrisemory** [craftcms/demo#22]
I just setup the Happy Lager site following the README.md instructions. Everything worked until I tried to view one of the News entries. The CSS was not loading. In the _layouts/base.html file, I found:
```
<link rel="stylesheet" type="text/css" href="{{ siteUrl }}assets/fonts/stylesheet.css">
<link rel="stylesheet" type="text/css" href="{{ siteUrl }}assets/css/happylager.css">

```
Under Settings > Sites > Happy Lager (en) the Base URL was not set. It might be helpful to add a note in the README.md to set this field.

**Comment by brandonkelly** [comment]
This should be fixed now per 97b3a00486c7faea3e7fbcbdedf8f888f1d00f9d. Now the site URL is based on a `SITE_URL` environment variable, and a default value of `http://happylager.test` is provided by the `.env.example` file.
