### ISSUE TITLE
composer install "command not found" after clone

### ISSUE THREAD

**Issue by Bluedimensional** [craftcms/demo#29]
Hi all,

I just cloned the repo and was going to use it locally. I `cd` into `happylager.test` and then get 'command not found'. I haven't used git in a few months but pretty sure that should be working. Any ideas what i am missing?

thanks!
Ben

**Comment by fleaz** [comment]
Hey @Bluedimensional 
`composer` is the package manager of PHP and not part of this repository, so it's not a problem with git or this repo. 
You need to install composer on your system before you can use it.

Check the [Getting Started](https://getcomposer.org/doc/00-intro.md) of composer for installation instructions :)

**Comment by angrybrad** [comment]
@Bluedimensional what @fleaz said. :)
