### ISSUE TITLE
Security key for fresh install

### ISSUE THREAD

**Issue by LarryBarker** [craftcms/demo#31]
### Description
There is no mention in the README on how to generate a security key for the application. A fresh install throws an exception because no key is present in the env file.

Is there a recommended approach to generating this value? 

### Steps to reproduce

1. Install the project following README instructions
2. Load the site in browser
3. Presented with error that key is required

### Additional info

- Craft version: Latest?
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions: N/A

**Comment by craftedsystems** [comment]
Follow the manual: [Set the Key from Your Terminal](https://craftcms.com/docs/3.x/installation.html#set-the-key-from-your-terminal)
```
php craft setup/security-key
```
The value in the `.env` file will be updated with a (new) key.  ✅

**Comment by angrybrad** [comment]
Added a step to the readme that explains this: https://github.com/craftcms/demo/commit/5708ffec1c1f09638ac0f83b2a8c0295fc80c121
